#:schema node_modules/wrangler/config-schema.json
name = "twikoo-worker"
main = "src/index.js"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
BUCKET_URL = "https://www.example.com"
# 修改你的bucket url，指向你的r2 存储桶

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "bucket"  # 修改为你图床的bucket名称

